### ISSUE TITLE
TASK: Title Screen (Start Button Functionality)

### ISSUE THREAD

**Issue by tcraven96** [tcraven96/CSE-442#2]
As a developer, I want a title screen with a start button so I can start the game.

**Comment by ZakProhn** [comment]
# Acceptence Test
Step 1 - Load up the game which should bring up a menu containing a "Start Game" button
Step 2 - Use mouse and mouse button or Select the button with the keyboard's arrow keys and press enter. This should load a new game with a  character sprite in the center of the screen.

**Comment by tcraven96** [comment]
Created Title Screen (First Draft)

Utilizing https://ezgif.com, videos taken from my iPhone, and a font called Poiret One I was able to create a demo version of our title screen. Will check with other team members for input. Includes title of game & blinking "press enter" caption. No functionality as of yet. Simply wanted to start working on the Title Screen.

**Comment by tcraven96** [comment]
Accidentally closed issue, still learning the ins & outs of ZenHub.

**Comment by ZakProhn** [comment]
We have confirmed functionality and are closing this task.
