### ISSUE TITLE
TASK: Title Screen (Exit Game)

### ISSUE THREAD

**Issue by tcraven96** [tcraven96/CSE-442#4]
As a developer, I want to be able to provide an exit mechanic from the title screen so we can easily end game sessions without leaving the application.

**Comment by ZakProhn** [comment]
#Acceptance Test

Step 1: On the menu using the arrow keys and enter button on the "EXIT GAME" button should close out of the window the game is currently being played in.

**Comment by tcraven96** [comment]
Exit game functionality has been created. Additional hovering over exit game icon turns yellow was added for increased intuitive use. 

Ran Acceptance Test. 
Acceptance Test Satisfied.

**Comment by ZakProhn** [comment]
Functionality has been implemented and we can now close this issue.
